import Link from 'next/link'

const TIERS = [
  {
    name: 'Starter',
    price: 'Free',
    period: null,
    description: 'Try the full pipeline before you commit.',
    limit: '5 briefs / month',
    features: [
      'Full SEO brief (title, meta, H2s, gaps)',
      'Content gap analysis',
      'Internal linking suggestions',
      '1 article draft per brief',
    ],
    cta: 'Start free',
    href: '/',
    accent: false,
  },
  {
    name: 'Pro',
    price: '$29',
    period: '/ month',
    description: 'For writers and operators publishing consistently.',
    limit: '60 briefs / month',
    features: [
      'Everything in Starter',
      'Unlimited article drafts',
      'Brief history & saved drafts',
      'Export to Markdown or Google Docs',
      'Priority generation queue',
    ],
    cta: 'Get Pro',
    href: '/',
    accent: true,
  },
  {
    name: 'Agency',
    price: '$99',
    period: '/ month',
    description: 'For teams running content at scale.',
    limit: 'Unlimited briefs',
    features: [
      'Everything in Pro',
      'Team seats (up to 10)',
      'Client workspace isolation',
      'API access',
      'Dedicated support',
    ],
    cta: 'Contact us',
    href: 'mailto:hello@microgen.io',
    accent: false,
  },
]

const FAQ = [
  {
    q: 'What counts as a "brief"?',
    a: 'One keyword submission that produces a brief. Generating an article from that brief does not use an additional brief credit.',
  },
  {
    q: 'Which AI model runs the generation?',
    a: 'Briefs and articles are generated by Gemini 2.5. We route to the best available model for each task.',
  },
  {
    q: 'Can I export the output?',
    a: 'Pro and Agency plans can export briefs and articles to Markdown or Google Docs. Starter output can be copied to clipboard.',
  },
  {
    q: 'Is there a contract on Pro or Agency?',
    a: 'No. Both plans are month-to-month and cancel any time from your account settings.',
  },
]

export default function Pricing() {
  return (
    <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
      <Header />

      <main style={{ flex: 1, padding: '48px 32px 96px' }}>
        <div style={{ maxWidth: 760, margin: '0 auto' }}>

          {/* Hero */}
          <div style={{ marginBottom: 64 }}>
            <div className="mono" style={{
              fontSize: 11, color: 'var(--mute)', letterSpacing: '0.1em',
              textTransform: 'uppercase', marginBottom: 20,
            }}>Pricing</div>
            <h1 style={{
              margin: 0, fontSize: 56, fontWeight: 400,
              letterSpacing: '-0.04em', lineHeight: 1.0, color: 'var(--ink)',
            }}>
              Simple plans.<br/>
              <span className="serif" style={{ fontStyle: 'italic' }}>No surprises.</span>
            </h1>
            <p style={{
              marginTop: 24, fontSize: 17, color: 'var(--ink-2)',
              lineHeight: 1.55, letterSpacing: '-0.005em', maxWidth: 480,
            }}>
              Start free. Upgrade when you need volume or want to keep your brief history.
            </p>
          </div>

          {/* Tiers */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
            {TIERS.map((tier, i) => (
              <TierRow key={i} tier={tier} />
            ))}
          </div>

          {/* FAQ */}
          <section style={{ marginTop: 96 }}>
            <h2 style={{
              margin: '0 0 40px', fontSize: 28, fontWeight: 400,
              letterSpacing: '-0.025em', color: 'var(--ink)',
            }}>Common questions</h2>
            <div style={{ borderTop: '1px solid var(--line)' }}>
              {FAQ.map((item, i) => (
                <div key={i} style={{
                  padding: '28px 0',
                  borderBottom: '1px solid var(--line)',
                  display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 48,
                }}>
                  <p style={{
                    margin: 0, fontSize: 16, fontWeight: 500,
                    color: 'var(--ink)', letterSpacing: '-0.015em', lineHeight: 1.4,
                  }}>{item.q}</p>
                  <p style={{
                    margin: 0, fontSize: 15, color: 'var(--ink-2)',
                    lineHeight: 1.6, letterSpacing: '-0.005em',
                  }}>{item.a}</p>
                </div>
              ))}
            </div>
          </section>

        </div>
      </main>
    </div>
  )
}

function TierRow({ tier }) {
  return (
    <div style={{
      padding: '32px 0',
      borderBottom: '1px solid var(--line)',
      display: 'grid',
      gridTemplateColumns: '180px 1fr auto',
      gap: 48,
      alignItems: 'start',
      ...(tier.accent ? {
        background: 'var(--paper)',
        borderRadius: 12,
        padding: '32px 28px',
        margin: '0 -28px',
        border: '1px solid var(--line)',
      } : {}),
    }}>
      {/* Left: name + price */}
      <div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12 }}>
          <span style={{
            fontSize: 15, fontWeight: 500, color: 'var(--ink)', letterSpacing: '-0.02em',
          }}>{tier.name}</span>
          {tier.accent && (
            <span style={{
              fontSize: 10, fontWeight: 500, padding: '2px 8px',
              background: 'var(--accent-soft)', color: 'var(--accent)',
              borderRadius: 999, letterSpacing: '0.04em',
              fontFamily: 'var(--font-mono)', textTransform: 'uppercase',
            }}>Popular</span>
          )}
        </div>
        <div style={{ display: 'flex', alignItems: 'baseline', gap: 4 }}>
          <span style={{
            fontSize: 36, fontWeight: 400, color: 'var(--ink)',
            letterSpacing: '-0.04em', lineHeight: 1,
          }}>{tier.price}</span>
          {tier.period && (
            <span className="mono" style={{ fontSize: 12, color: 'var(--mute)' }}>{tier.period}</span>
          )}
        </div>
        <div className="mono" style={{
          marginTop: 8, fontSize: 11, color: 'var(--mute)',
          letterSpacing: '0.04em',
        }}>{tier.limit}</div>
      </div>

      {/* Middle: features */}
      <div>
        <p style={{
          margin: '0 0 16px', fontSize: 14, color: 'var(--ink-2)',
          lineHeight: 1.55, letterSpacing: '-0.005em',
        }}>{tier.description}</p>
        <ul style={{ margin: 0, padding: 0, listStyle: 'none' }}>
          {tier.features.map((f, i) => (
            <li key={i} style={{
              display: 'flex', gap: 10, padding: '5px 0',
              fontSize: 14, color: 'var(--ink-2)', letterSpacing: '-0.005em',
            }}>
              <span style={{ color: 'var(--accent)', flexShrink: 0, marginTop: 1 }}>→</span>
              <span>{f}</span>
            </li>
          ))}
        </ul>
      </div>

      {/* Right: CTA */}
      <div style={{ paddingTop: 4 }}>
        <a href={tier.href} style={{
          display: 'inline-flex', alignItems: 'center',
          padding: '10px 18px', borderRadius: 8,
          fontSize: 13.5, fontWeight: 500, letterSpacing: '-0.01em',
          whiteSpace: 'nowrap', cursor: 'pointer',
          background: tier.accent ? 'var(--ink)' : 'transparent',
          color: tier.accent ? 'var(--bg)' : 'var(--ink)',
          border: tier.accent ? 'none' : '1px solid var(--line)',
        }}>{tier.cta} →</a>
      </div>
    </div>
  )
}

function Header() {
  return (
    <header style={{
      display: 'flex', justifyContent: 'space-between', alignItems: 'center',
      padding: '20px 32px',
    }}>
      <Wordmark />
      <nav style={{ display: 'flex', gap: 28, fontSize: 14, color: 'var(--ink-2)', whiteSpace: 'nowrap' }}>
        <Link href="/examples">Examples</Link>
        <Link href="/pricing" style={{ color: 'var(--ink)', fontWeight: 500 }}>Pricing</Link>
      </nav>
    </header>
  )
}

function Wordmark() {
  return (
    <Link href="/" style={{ display: 'inline-flex', alignItems: 'center', gap: 9 }}>
      <Logo />
      <span style={{ fontWeight: 500, fontSize: 15, letterSpacing: '-0.025em', color: 'var(--ink)' }}>
        microgen
      </span>
    </Link>
  )
}

function Logo({ size = 22 }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <rect x="2.5" y="4.5" width="19" height="15" rx="2.5" stroke="var(--ink)" strokeWidth="1.4" />
      <rect x="5" y="7" width="3" height="2" rx="0.5" fill="var(--ink)" />
      <rect x="9" y="7" width="3" height="2" rx="0.5" fill="var(--ink)" />
      <rect x="13" y="7" width="3" height="2" rx="0.5" fill="var(--ink)" />
      <rect x="17" y="7" width="2" height="2" rx="0.5" fill="var(--accent)" />
      <rect x="5" y="10.5" width="14" height="2" rx="0.5" fill="var(--ink)" />
      <rect x="5" y="14" width="9" height="2" rx="0.5" fill="var(--ink)" />
    </svg>
  )
}
